config/routes.rb
Rails.application.routes.draw do

  resources :auction_participants

  get 'users/new'

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'blog'  => 'static_pages#blog'
  get 'signup'  => 'users#new'

  resources :users

  resources :auctions

  resources :events do
    resources :rounds
    resources :entrants
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_one :event

  has_many :auction_participants
  has_many :users, through: :auction_participants
end

app/models/auction_participant.rb
class AuctionParticipant < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rounds, dependent: :destroy
  has_many :entrants, dependent: :destroy
  has_many :auctions



end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :event, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :auction_participants
  has_many :auctions, through: :auction_participants

  before_save {self.email = email.downcase}

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_senstive: false}

  has_secure_password
  validates :password, length: {minimum: 6}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def new
    @auction = Auction.new
  end

  def show
    @auction = Auction.find(params[:id])
  end

  def create
    @auction = Auction.new(auction_params)
    if @auction.save
      flash[:success] = "Thanks for creating an auction"
      redirect_to @auction
    else
      render 'new'
    end
  end

  def index
    @auctions = Auction.all
  end


  private

  def auction_params
    params.require(:auction).permit(:name, :number_participants, :start, :event_id, :soft_cap)
  end



end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.create(entrant_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.find(params[:id])
    @entrant.destroy
    redirect_to event_path(@event)
  end

  private
    def entrant_params
      params.require(:entrant).permit(:name, :order, :seed)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :sport, :league, :start_date, :cutoff)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @round = @event.rounds.create(round_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @round = @event.rounds.find(params[:id])
    @round.destroy
    redirect_to event_path(@event)
  end

  private
    def round_params
      params.require(:round).permit(:name, :order, :payout)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @events = Event.all
    @users = User.all
  end

  def help
  end

  def about
  end

  def contact
  end

  def blog
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Calcutta Auction!"
      redirect_to @user
    else
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/auction_participants_helper.rb
module AuctionParticipantsHelper
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/round_helper.rb
module RoundHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end



end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/static_pages/_events.html.erb
<div id="wrapper">
  <h1>All Events</h1>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Sport</th>
        <th>League</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.sport %></td>
          <td><%= event.league %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path %>
</div>

app/views/static_pages/_users.html.erb
<div id="wrapper">
  <h1>All Site Users</h1>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>email</th>
        <th>Profile Page</th>

      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'profile', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/about.html.erb
<div id="wrapper">
  <h1> What is a calcultta auction?<h1>

  <p>
    "A Calcutta auction (also known simply as a ""Calcutta"") [1] is an open auction held in conjunction with a golf tournament,[2] horse race or similar contest with multiple entrants. It is popular in backgammon, the Melbourne Cup, and college basketball pools during March Madness[3] (originally in Calcutta, India, from where this technique was first recorded by the Colonial British) bid among themselves to ""buy"" each of the contestants, with each contestant being assigned to the highest bidder. The contestant will then pay out to the owner a predetermined proportion of the pool depending on how it performs in the tournament. While variations in payoff schedules exist, in an NCAA Basketball tournament (64 teams, single elimination) the payoffs could resemble the following schedule: 1 win - 0.25%, 2 wins - 2%, 3 wins - 4%, 4 wins - 8%, 5 wins - 16%, tournament winner with 6 wins - 32%.
  </p>
  <p>
    The precise rules of a Calcutta can vary from place to place; many tournament organizers employ software programs that apply odds and determine win-place-show amounts. Perhaps the simplest and most common Calcutta payout is 70 percent of the pool to the ""owner"" of the winning tournament team, 30 percent to the ""owner"" of the second-place tournament team.
  </p>
  <p>
    An interesting element of Calcutta auctions is in determining an appropriate wager for each contestant, as the payoff will directly hinge on the size of the pot and thereby the size of the bids being placed. Thus the value of each team fluctuates during the course of the betting. For example, even if a bidder knew the University of North Carolina would be the tournament winner and thus pay out 32% of the pool, she would still be unsure of the exact value of the team (unless it was the last team being bid on) since the payout depends on the sum total of all winning bids, i.e. the final size of the pool.
  </p>
  <p>
    Another typical variation in NCAA Calcutta auctions is the bundling and auctioning off as a block the lowest seeded teams in each region, called the ""Dogs"". For example, the 16th to 13th seeded teams from the Midwest Region would be bid upon as a bundle named the ""Dogs of the Midwest"". The winning bidder would own all 4 teams and usually recoups his or her investment if one or two of the Dogs wins an upset.
  </p>
  <p>
    There are two important steps in determining how much we are willing to pay for a team in Calcutta-style pools:
  </p>
  <ol>
    <li>Determine what % of the total pot we are willing to pay for a contestant.</li>
    <li>Convert this % into an actual dollar amount.</li>
  </ol>
  <p>
    This process produces a “fair value” of the team. With this information in hand, you can objectively determine which teams are under-valued (i.e. they are bid below fair value) and attempt to purchase them."
  </p>
</div>

app/views/static_pages/blog.html.erb
<h1>Blog</h1>
<p>This page will be either a live feed from a different blog site or I'll create another controller for site admins
to be able to post to.</p>

app/views/static_pages/contact.html.erb
<h1>Contact Page</h1>
<p>This is where contact info will go. Maybe we dont't need a whole page, but an email form would be nice.</p>

app/views/static_pages/help.html.erb
<h1>Help Page</h1>
<p>Probably won't need this now, or maybe ever. Probably a waste of bytes.</p>

app/views/static_pages/home.html.erb
<div id="wrapper">

  <h1>Welcome to CalcuttaAuction.com</h1>

  <section>
    <ul id="gallery">
      <li>
        <a href=<%= about_path %>>
          <p>What is calcutta a auction?</p>
        </a>
      </li>
      <li>
        <a href=<%= blog_path %>>
          <p>Learn more by following our blog</p>
        </a>
      </li>
    </ul>
    <div>
      <h3>Start Playing Today!</h3>
        <ul id="gallery">
          <li>
            <a href=<%= new_auction_path %>>
              <p>Host an Auction</p>
            </a>
          </li>
          <li>
            <a href=<%= auctions_path %>>
              <p>Join an Auction</p>
            </a>
          </li>
        </ul>
  </section>

  <h3>temporary links for administrators</h3>
  <ul>
    <li><%= link_to 'Events', events_path %></li>
    <div>
      <%= render 'events' %>
    </div>
    <div>
      <%= render 'users' %>
    </div>



</div>