config/routes.rb
Rails.application.routes.draw do

  resources :auction_participants

  get 'users/new'

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'blog'  => 'static_pages#blog'
  get 'signup'  => 'users#new'

  resources :users

  resources :auctions

  resources :events do
    resources :rounds
    resources :entrants
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_one :event

  has_many :auction_participants
  has_many :users, through: :auction_participants
end

app/models/auction_participant.rb
class AuctionParticipant < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rounds, dependent: :destroy
  has_many :entrants, dependent: :destroy
  has_many :auctions



end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :event, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :auction_participants
  has_many :auctions, through: :auction_participants

  before_save {self.email = email.downcase}

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_senstive: false}

  has_secure_password
  validates :password, length: {minimum: 6}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auction_participants_controller.rb
class AuctionParticipantsController < ApplicationController
  before_action :set_auction_participant, only: [:show, :edit, :update, :destroy]

  # GET /auction_participants
  # GET /auction_participants.json
  def index
    @auction_participants = AuctionParticipant.all
  end

  # GET /auction_participants/1
  # GET /auction_participants/1.json
  def show
  end

  # GET /auction_participants/new
  def new
    @auction_participant = AuctionParticipant.new
  end

  # GET /auction_participants/1/edit
  def edit
  end

  # POST /auction_participants
  # POST /auction_participants.json
  def create
    @auction_participant = AuctionParticipant.new(auction_participant_params)

    respond_to do |format|
      if @auction_participant.save
        format.html { redirect_to @auction_participant, notice: 'Auction participant was successfully created.' }
        format.json { render :show, status: :created, location: @auction_participant }
      else
        format.html { render :new }
        format.json { render json: @auction_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auction_participants/1
  # PATCH/PUT /auction_participants/1.json
  def update
    respond_to do |format|
      if @auction_participant.update(auction_participant_params)
        format.html { redirect_to @auction_participant, notice: 'Auction participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction_participant }
      else
        format.html { render :edit }
        format.json { render json: @auction_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auction_participants/1
  # DELETE /auction_participants/1.json
  def destroy
    @auction_participant.destroy
    respond_to do |format|
      format.html { redirect_to auction_participants_url, notice: 'Auction participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction_participant
      @auction_participant = AuctionParticipant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_participant_params
      params[:auction_participant].permit(:auction_id, :user_id, :owner_flag)
    end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def new
    @auction = Auction.new
  end

  def show
    @auction = Auction.find(params[:id])
  end

  def create
    @auction = Auction.new(auction_params)
    if @auction.save
      flash[:success] = "Thanks for creating an auction"
      redirect_to @auction
    else
      render 'new'
    end
  end

  def index
    @auctions = Auction.all
  end


  private

  def auction_params
    params.require(:auction).permit(:name, :number_participants, :start, :event_id, :soft_cap)
  end



end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.create(entrant_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.find(params[:id])
    @entrant.destroy
    redirect_to event_path(@event)
  end

  private
    def entrant_params
      params.require(:entrant).permit(:name, :order, :seed)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :sport, :league, :start_date, :cutoff)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @round = @event.rounds.create(round_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @round = @event.rounds.find(params[:id])
    @round.destroy
    redirect_to event_path(@event)
  end

  private
    def round_params
      params.require(:round).permit(:name, :order, :payout)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @events = Event.all
    @users = User.all
  end

  def help
  end

  def about
  end

  def contact
  end

  def blog
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Calcutta Auction!"
      redirect_to @user
    else
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/auction_participants_helper.rb
module AuctionParticipantsHelper
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/round_helper.rb
module RoundHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end



end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auction_participants/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@auction_participant) do |f| %>
      <% if @auction_participant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@auction_participant.errors.count, "error") %> prohibited this auction_participant from being saved:</h2>

          <ul>
          <% @auction_participant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :user %>
      <%= f.number_field :user_id, class: 'form-control'  %>

      <%= f.label :auction %>
      <%= f.number_field :auction_id, class: 'form-control'  %>

      <%= f.label :owner %>
      <%= f.radio_button :owner_flag, class: 'form-control'  %>



      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/auction_participants/edit.html.erb
<h1>Editing auction_participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction_participant %> |
<%= link_to 'Back', auction_participants_path %>

app/views/auction_participants/index.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">

    <h1>Listing auction_participants</h1>

    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>User</th>
          <th>Auction</th>
          <th>Onwer?</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @auction_participants.each do |auction_participant| %>
          <tr>
            <td><%= auction_participant.user_id %></td>
            <td><%= auction_participant.auction_id %></td>
            <td><%= auction_participant.owner_flag %></td>
            <td><%= link_to 'Show', auction_participant %></td>
            <td><%= link_to 'Edit', edit_auction_participant_path(auction_participant) %></td>
            <td><%= link_to 'Destroy', auction_participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Auction participant', new_auction_participant_path %>

app/views/auction_participants/new.html.erb
<h1>New auction_participant</h1>

<%= render 'form' %>

<%= link_to 'Back', auction_participants_path %>

app/views/auction_participants/show.html.erb
<div class="row">
  <div class="col-md-4">
    <p id="notice"><%= notice %></p>
    <p>Auction ID: <%= @auction_participant.auction_id %></p>
    <p>User ID: <%= @auction_participant.user_id %></p>
    <p>Owner Flag: <%= @auction_participant.owner_flag %></p>

    <%= link_to 'Edit', edit_auction_participant_path(@auction_participant) %> |
    <%= link_to 'Back', auction_participants_path %>

  </div>
</div>

app/views/auctions/index.html.erb
<h1>Auctions Page</h1>
<p>This page will list all available auctions.</p>
<p>Not sure about long term strategy about listing every available auction to every person,
  but for now we will list them all and this is where users will join an auction.</p>




<div id="wrapper">
  <h1>All Available Auctions</h1>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Event</th>
        <th>Spots</th>
        <th>Filled Spots</th>
        <th>Available Spots</th>
        <th>Soft Cap</th>
        <th>Auction Date</th>
        <th>Time Remaning</th>
        <th>Join Auction!</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @auctions.each do |auction| %>
        <tr>
          <td><%= auction.name %></td>
          <td><%= auction.event_id %></td>
          <td><%= auction.number_participants %></td>
          <td>Coming soon</td>
          <td>Coming soon</td>
          <td><%= auction.soft_cap%></td>
          <td><%= auction.start %></td>
          <td>Coming soon</td>
          <td>Coming soon</td>
          <td><%= link_to 'Show', auction %></td>
          <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
          <td><%= link_to 'Delete', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Create Another Auction', new_auction_path , :class => "btn btn-primary" %>
</div>

app/views/auctions/new.html.erb
<h1>Create a New Auction</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@auction) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :event %>
      <%= f.number_field :event_id, class: 'form-control'  %>

      <%= f.label :number_participants %>
      <%= f.number_field :number_participants, class: 'form-control' %>

      <%= f.label :start %>
      <%= f.date_field :start, class: 'form-control' %>

      <%= f.label :soft_cap %>
      <%= f.number_field :soft_cap, class: 'form-control' %>

      <%= f.submit "Create an auction", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/auctions/show.html.erb
<div class="container">
  <div class="row">

    <h1>Admin View of an auction</h1>
    <p> Still need to add an edit action, don't click yet <%= link_to 'Edit', edit_auction_path(@auction) %></p>

    <h3>Auction Paramters</h3>
    <p>Auction name: <%= @auction.name %></p>
    <p>Max Particpants: <%= @auction.number_participants %></p>
    <!-- I know this line is wrong, need to fix -->
    <p>Event: <%= Event.find(@auction.event_id).name %></p>
    <p>Start Date: <%= @auction.start %></p>
    <p>Soft Cap: <%= @auction.soft_cap %></p>

  </div>

  <div class="row">
    <div class="col-md-4">
      <h3>Auction Participants</h3>

      <%= @auction.users.each do |participant| %>
      <p><%= participant.name %></p>
        <% end %>


    </div>
  </div>





</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :league %><br>
    <%= f.text_field :league %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :cutoff %><br>
    <%= f.datetime_select :cutoff %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="wrapper">
  <h1>Listing events</h1>

  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Sport</th>
        <th>League</th>
        <th>Start date</th>
        <th>Cutoff</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.sport %></td>
          <td><%= event.league %></td>
          <td><%= event.start_date %></td>
          <td><%= event.cutoff %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event', new_event_path, :class => "btn btn-primary" %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div id="wrapper">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Sport:</strong>
    <%= @event.sport %>
  </p>

  <p>
    <strong>League:</strong>
    <%= @event.league %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @event.start_date %>
  </p>

  <p>
    <strong>Cutoff:</strong>
    <%= @event.cutoff %>
  </p>

  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>



  </br></br></br>


<div class ="row">
  <div class="col-md-6">

    <h2>Entrants Section</h2></br></br>

    <h2>Add an Entrant:</h2>
    <%= form_for([@event, @event.entrants.build]) do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :order %><br>
        <%= f.number_field :order %>
      </p>
      <p>
        <%= f.submit %>
      </p>
    <% end %>

    </br></br></br>

    <h2>Entrants</h2>

    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Seed</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @event.entrants.each do |entrant| %>
        <tr>
          <td><%= entrant.name %></td>
          <td><%= entrant.seed %></td>
          <td><%= link_to 'Delete Entrant', [entrant.event, entrant],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <div class="col-md-6">

  <h2>Rounds Section:</h2></br></br>

  <h2>Add a Round:</h2>

  <%= form_for([@event, @event.rounds.build]) do |f| %>
    <div class="field">
      <%= f.label :name %></br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :order %></br>
      <%= f.number_field :order %>
    </div>
    <div class="field">
      <%= f.label :payout %></br>
      <%= f.text_field :payout %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  </br>

  <h2>Rounds</h2>


  <table class="table table-striped table-condensed">
    <head>
      <tr>
        <th>Name</th>
        <th>Order</th>
        <th>Payout %</th>
        <th></th>
      </tr>
    </head>

    <tbody>
      <% @event.rounds.each do |round| %>
      <tr>
        <td><%= round.name %></td>
        <td><%= round.order %></td>
        <td><%= round.payout %></td>
        <td><%= link_to 'Delete Round', [round.event, round],
                     method: :delete,
                     data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>







</div>

app/views/rounds/new.html.erb
<h1>hi ryan</h1>
<p>something else</p>

<%= form_for [@event, @round] do |f| %>
  <div class="field">
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order %></br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :payout %></br>
    <%= f.number_field :payout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>