config/routes.rb
Rails.application.routes.draw do

  resources :auction_participants

  get 'users/new'

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'blog'  => 'static_pages#blog'
  get 'signup'  => 'users#new'

  resources :users

  resources :auctions

  resources :events do
    resources :rounds
    resources :entrants
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_one :event

  has_many :auction_participants
  has_many :users, through: :auction_participants
end

app/models/auction_participant.rb
class AuctionParticipant < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rounds, dependent: :destroy
  has_many :entrants, dependent: :destroy
  has_many :auctions



end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :event, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :auction_participants
  has_many :auctions, through: :auction_participants

  before_save {self.email = email.downcase}

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_senstive: false}

  has_secure_password
  validates :password, length: {minimum: 6}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def new
    @auction = Auction.new
  end

  def show
    @auction = Auction.find(params[:id])
  end

  def create
    @auction = Auction.new(auction_params)
    if @auction.save
      flash[:success] = "Thanks for creating an auction"
      redirect_to @auction
    else
      render 'new'
    end
  end

  def index
    @auctions = Auction.all
  end


  private

  def auction_params
    params.require(:auction).permit(:name, :number_participants, :start, :event_id, :soft_cap)
  end



end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.create(entrant_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @entrant = @event.entrants.find(params[:id])
    @entrant.destroy
    redirect_to event_path(@event)
  end

  private
    def entrant_params
      params.require(:entrant).permit(:name, :order, :seed)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :sport, :league, :start_date, :cutoff)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @round = @event.rounds.create(round_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @round = @event.rounds.find(params[:id])
    @round.destroy
    redirect_to event_path(@event)
  end

  private
    def round_params
      params.require(:round).permit(:name, :order, :payout)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Calcutta Auction!"
      redirect_to @user
    else
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/round_helper.rb
module RoundHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end



end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calcutta3</title>
  <link rel="stylesheet" href="css/normalize.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Changa+One:400,400italic|Open+Sans:600italic,400,700|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/responsive.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <header>
    <a href=<%= root_path %> id="logo">
      <h1>Calcutta Auction</h1>
      <h2>Host your auction today</h2>
    </a>

    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blog", blog_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
      </ul>
    </nav>

  </header>


  
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>

  <!-- <footer>
    <a href="http://twitter.com"><img src="img/twitter-wrap.png" alt="Twitter Logo" class="social-icon"></a>
    <a href="http://facebook.com"><img src="img/facebook-wrap.png" alt="Facebook Logo" class="social-icon"></a>
    <p>&copy; 2014 Ryan Dorr.</p>

  </footer> -->





</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>